#! /bin/sh

chmod 777 /oem/partybox_play.sh

/oem/partybox_play.sh &

sync

start() {
	ulimit -c unlimited
	echo "/tmp/core-%p-%e.$(date "+%Y%m%d_%H%M%S")" > /proc/sys/kernel/core_pattern
	chmod 777 /oem/partybox_app.sh
	/oem/partybox_app.sh &
}

case "$1" in
  start)
	start
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
