#! /bin/sh

chmod 777 /data/partybox_play.sh
chmod 777 /data/rk_karaoke_test.sh

/data/partybox_play.sh &
sync

start() {
	ulimit -c unlimited
	echo "/tmp/core-%p-%e.$(date "+%Y%m%d_%H%M%S")" > /proc/sys/kernel/core_pattern
	sleep 1
	chmod 777 /data/S99-rkpartybox
	/data/S99-rkpartybox &
}

case "$1" in
  start)
	start
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
