#ifndef _PARAM__H__
#define _PARAM__H__


/* Module MULTI_INPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_INPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module SINGLE_VOLUME_0 Location Start - Non Modulo Location Start*/
#define SINGLE_VOLUME_0_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SINGLE_VOLUME_0_VOLUME_ADDR  32768
#define SINGLE_VOLUME_0_VOLUME_VALUE  0


/* Module SPLITTER_SINGLE_0 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_0_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_0_GAIN_ADDR  65536
#define SPLITTER_SINGLE_0_GAIN_VALUE  0.0


/* Module SPLITTER_SINGLE_1 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_1_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_1_GAIN_ADDR  98304
#define SPLITTER_SINGLE_1_GAIN_VALUE  0.0


/* Module MIXER_MULTI_0 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_0_G0_ADDR  131072
#define MIXER_MULTI_0_G0_VALUE  -6.0
#define MIXER_MULTI_0_G1_ADDR  131073
#define MIXER_MULTI_0_G1_VALUE  -6.0


/* Module SPLITTER_SINGLE_2 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_2_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_2_GAIN_ADDR  163840
#define SPLITTER_SINGLE_2_GAIN_VALUE  0.0


/* Module DSP_GAIN_2 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_2_GAIN_ADDR  196608
#define DSP_GAIN_2_GAIN_VALUE  3.0
#define DSP_GAIN_2_TYPE_ADDR  196609
#define DSP_GAIN_2_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_1 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_1_COUNT    45

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_ADDR  229376
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_VALUE  11
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229377
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229378
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229379
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229380
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229381
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229382
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229383
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229384
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229385
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229386
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229387
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229388
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229389
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229390
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229391
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229392
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229393
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229394
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229395
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229396
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229397
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229398
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229399
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229400
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229401
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229402
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229403
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229404
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229405
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229406
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229407
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229408
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229409
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  50.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229410
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229411
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  1.2
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229412
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229413
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  85.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229414
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229415
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229416
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_FC_ADDR  229417
#define FILTER_GRAPHICAL_EQ_1_FC_VALUE  2000.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_ADDR  229418
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_VALUE  -7.0
#define FILTER_GRAPHICAL_EQ_1_Q_ADDR  229419
#define FILTER_GRAPHICAL_EQ_1_Q_VALUE  1.7
#define FILTER_GRAPHICAL_EQ_1_TYPE_ADDR  229420
#define FILTER_GRAPHICAL_EQ_1_TYPE_VALUE  0


/* Module DSP_GAIN_3 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_3_GAIN_ADDR  262144
#define DSP_GAIN_3_GAIN_VALUE  6.0
#define DSP_GAIN_3_TYPE_ADDR  262145
#define DSP_GAIN_3_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_0 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_0_COUNT    45

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_ADDR  294912
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_VALUE  11
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294913
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294914
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294915
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294916
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294917
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294918
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294919
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294920
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294921
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294922
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294923
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294924
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294925
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294926
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294927
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294928
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294929
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294930
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294931
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294932
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294933
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294934
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294935
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294936
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294937
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294938
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294939
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294940
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294941
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294942
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294943
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294944
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294945
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  2200.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294946
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  -5.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294947
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294948
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294949
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  7000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294950
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294951
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  3.5
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294952
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_FC_ADDR  294953
#define FILTER_GRAPHICAL_EQ_0_FC_VALUE  13000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_ADDR  294954
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_VALUE  2.0
#define FILTER_GRAPHICAL_EQ_0_Q_ADDR  294955
#define FILTER_GRAPHICAL_EQ_0_Q_VALUE  1.41
#define FILTER_GRAPHICAL_EQ_0_TYPE_ADDR  294956
#define FILTER_GRAPHICAL_EQ_0_TYPE_VALUE  0


/* Module LIMITER_0 Location Start - Non Modulo Location Start*/
#define LIMITER_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_0_RMSTC_ADDR  327680
#define LIMITER_0_RMSTC_VALUE  20.0
#define LIMITER_0_DECAYTIME_ADDR  327681
#define LIMITER_0_DECAYTIME_VALUE  200.0
#define LIMITER_0_THRESHOLD_ADDR  327682
#define LIMITER_0_THRESHOLD_VALUE  -12.5


/* Module DSP_GAIN_1 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_1_GAIN_ADDR  360448
#define DSP_GAIN_1_GAIN_VALUE  0.0
#define DSP_GAIN_1_TYPE_ADDR  360449
#define DSP_GAIN_1_TYPE_VALUE  0


/* Module MUTE_3 Location Start - Non Modulo Location Start*/
#define MUTE_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_3_SWITCH_ADDR  393216
#define MUTE_3_SWITCH_VALUE  False
#define MUTE_3_SLEWFLAG_ADDR  393217
#define MUTE_3_SLEWFLAG_VALUE  True


/* Module LIMITER_1 Location Start - Non Modulo Location Start*/
#define LIMITER_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_1_RMSTC_ADDR  425984
#define LIMITER_1_RMSTC_VALUE  2.0
#define LIMITER_1_DECAYTIME_ADDR  425985
#define LIMITER_1_DECAYTIME_VALUE  1000.0
#define LIMITER_1_THRESHOLD_ADDR  425986
#define LIMITER_1_THRESHOLD_VALUE  -12.5


/* Module DSP_GAIN_0 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_0_GAIN_ADDR  458752
#define DSP_GAIN_0_GAIN_VALUE  0.0
#define DSP_GAIN_0_TYPE_ADDR  458753
#define DSP_GAIN_0_TYPE_VALUE  0


/* Module MUTE_5 Location Start - Non Modulo Location Start*/
#define MUTE_5_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_5_SWITCH_ADDR  491520
#define MUTE_5_SWITCH_VALUE  False
#define MUTE_5_SLEWFLAG_ADDR  491521
#define MUTE_5_SLEWFLAG_VALUE  True


/* Module DSP_GAIN_4 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_4_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_4_GAIN_ADDR  524288
#define DSP_GAIN_4_GAIN_VALUE  0.0
#define DSP_GAIN_4_TYPE_ADDR  524289
#define DSP_GAIN_4_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_2 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_2_COUNT    45

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_2_NUMFILTER_ADDR  557056
#define FILTER_GRAPHICAL_EQ_2_NUMFILTER_VALUE  11
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557057
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557058
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557059
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557060
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557061
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557062
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557063
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557064
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557065
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557066
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557067
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557068
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557069
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557070
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557071
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557072
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557073
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557074
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557075
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557076
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557077
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557078
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557079
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557080
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557081
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557082
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557083
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557084
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557085
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557086
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557087
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557088
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557089
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  2200.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557090
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  -5.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557091
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557092
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557093
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  7000.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557094
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557095
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  3.5
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557096
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  0
#define FILTER_GRAPHICAL_EQ_2_FC_ADDR  557097
#define FILTER_GRAPHICAL_EQ_2_FC_VALUE  13000.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_ADDR  557098
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_VALUE  2.0
#define FILTER_GRAPHICAL_EQ_2_Q_ADDR  557099
#define FILTER_GRAPHICAL_EQ_2_Q_VALUE  1.41
#define FILTER_GRAPHICAL_EQ_2_TYPE_ADDR  557100
#define FILTER_GRAPHICAL_EQ_2_TYPE_VALUE  0


/* Module SPLITTER_SINGLE_4 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_4_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_4_GAIN_ADDR  589824
#define SPLITTER_SINGLE_4_GAIN_VALUE  0.0


/* Module ARITH_INVERT_1 Location Start - Non Modulo Location Start*/
#define ARITH_INVERT_1_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module SPLITTER_SINGLE_3 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_3_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_3_GAIN_ADDR  655360
#define SPLITTER_SINGLE_3_GAIN_VALUE  0.0


/* Module MIXER_MULTI_3 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_3_G0_ADDR  688128
#define MIXER_MULTI_3_G0_VALUE  -6.0
#define MIXER_MULTI_3_G1_ADDR  688129
#define MIXER_MULTI_3_G1_VALUE  -6.0


/* Module SPLITTER_SINGLE_5 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_5_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_5_GAIN_ADDR  720896
#define SPLITTER_SINGLE_5_GAIN_VALUE  0.0


/* Module MIXER_MULTI_1 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_1_G0_ADDR  753664
#define MIXER_MULTI_1_G0_VALUE  -5.0
#define MIXER_MULTI_1_G1_ADDR  753665
#define MIXER_MULTI_1_G1_VALUE  0.0


/* Module ARITH_INVERT_0 Location Start - Non Modulo Location Start*/
#define ARITH_INVERT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module MIXER_MULTI_2 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_2_G0_ADDR  819200
#define MIXER_MULTI_2_G0_VALUE  -5.0
#define MIXER_MULTI_2_G1_ADDR  819201
#define MIXER_MULTI_2_G1_VALUE  0.0


/* Module MUXES_SWITCH_STEREO_0 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_STEREO_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_STEREO_0_IDX_ADDR  851968
#define MUXES_SWITCH_STEREO_0_IDX_VALUE  0
#define MUXES_SWITCH_STEREO_0_SLEWFLAG_ADDR  851969
#define MUXES_SWITCH_STEREO_0_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_STEREO_0_SLEWRATE_ADDR  851970
#define MUXES_SWITCH_STEREO_0_SLEWRATE_VALUE  12


/* Module REVERB_0 Location Start - Non Modulo Location Start*/
#define REVERB_0_COUNT    6

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define REVERB_0_ENABLE_ADDR  884736
#define REVERB_0_ENABLE_VALUE  1
#define REVERB_0_DRYLEVEL_ADDR  884737
#define REVERB_0_DRYLEVEL_VALUE  80.0
#define REVERB_0_WETLEVEL_ADDR  884738
#define REVERB_0_WETLEVEL_VALUE  20.0
#define REVERB_0_ROOMSIZE_ADDR  884739
#define REVERB_0_ROOMSIZE_VALUE  0.65
#define REVERB_0_DAMP_ADDR  884740
#define REVERB_0_DAMP_VALUE  0.2
#define REVERB_0_WIDTH_ADDR  884741
#define REVERB_0_WIDTH_VALUE  60.0


/* Module MUXES_SWITCH_STEREO_1 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_STEREO_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_STEREO_1_IDX_ADDR  917504
#define MUXES_SWITCH_STEREO_1_IDX_VALUE  1
#define MUXES_SWITCH_STEREO_1_SLEWFLAG_ADDR  917505
#define MUXES_SWITCH_STEREO_1_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_STEREO_1_SLEWRATE_ADDR  917506
#define MUXES_SWITCH_STEREO_1_SLEWRATE_VALUE  12


/* Module DSP_GAIN_6 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_6_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_6_GAIN_ADDR  950272
#define DSP_GAIN_6_GAIN_VALUE  6.9
#define DSP_GAIN_6_TYPE_ADDR  950273
#define DSP_GAIN_6_TYPE_VALUE  0


/* Module LIMITER_3 Location Start - Non Modulo Location Start*/
#define LIMITER_3_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_3_RMSTC_ADDR  983040
#define LIMITER_3_RMSTC_VALUE  20.0
#define LIMITER_3_DECAYTIME_ADDR  983041
#define LIMITER_3_DECAYTIME_VALUE  200.0
#define LIMITER_3_THRESHOLD_ADDR  983042
#define LIMITER_3_THRESHOLD_VALUE  -12.5


/* Module SPLITTER_SINGLE_7 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_7_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_7_GAIN_ADDR  1015808
#define SPLITTER_SINGLE_7_GAIN_VALUE  0.0


/* Module MUTE_1 Location Start - Non Modulo Location Start*/
#define MUTE_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_1_SWITCH_ADDR  1048576
#define MUTE_1_SWITCH_VALUE  False
#define MUTE_1_SLEWFLAG_ADDR  1048577
#define MUTE_1_SLEWFLAG_VALUE  True


/* Module DSP_GAIN_5 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_5_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_5_GAIN_ADDR  1081344
#define DSP_GAIN_5_GAIN_VALUE  6.9
#define DSP_GAIN_5_TYPE_ADDR  1081345
#define DSP_GAIN_5_TYPE_VALUE  0


/* Module LIMITER_2 Location Start - Non Modulo Location Start*/
#define LIMITER_2_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_2_RMSTC_ADDR  1114112
#define LIMITER_2_RMSTC_VALUE  20.0
#define LIMITER_2_DECAYTIME_ADDR  1114113
#define LIMITER_2_DECAYTIME_VALUE  200.0
#define LIMITER_2_THRESHOLD_ADDR  1114114
#define LIMITER_2_THRESHOLD_VALUE  -12.5


/* Module SPLITTER_SINGLE_6 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_6_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_6_GAIN_ADDR  1146880
#define SPLITTER_SINGLE_6_GAIN_VALUE  0.0


/* Module MUXES_SWITCH_MONO_0 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_MONO_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_MONO_0_IDX_ADDR  1179648
#define MUXES_SWITCH_MONO_0_IDX_VALUE  0
#define MUXES_SWITCH_MONO_0_SLEWFLAG_ADDR  1179649
#define MUXES_SWITCH_MONO_0_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_MONO_0_SLEWRATE_ADDR  1179650
#define MUXES_SWITCH_MONO_0_SLEWRATE_VALUE  12


/* Module MUTE_4 Location Start - Non Modulo Location Start*/
#define MUTE_4_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_4_SWITCH_ADDR  1212416
#define MUTE_4_SWITCH_VALUE  False
#define MUTE_4_SLEWFLAG_ADDR  1212417
#define MUTE_4_SLEWFLAG_VALUE  True


/* Module MUXES_SWITCH_MONO_1 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_MONO_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_MONO_1_IDX_ADDR  1245184
#define MUXES_SWITCH_MONO_1_IDX_VALUE  0
#define MUXES_SWITCH_MONO_1_SLEWFLAG_ADDR  1245185
#define MUXES_SWITCH_MONO_1_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_MONO_1_SLEWRATE_ADDR  1245186
#define MUXES_SWITCH_MONO_1_SLEWRATE_VALUE  12


/* Module MUTE_2 Location Start - Non Modulo Location Start*/
#define MUTE_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_2_SWITCH_ADDR  1277952
#define MUTE_2_SWITCH_VALUE  False
#define MUTE_2_SLEWFLAG_ADDR  1277953
#define MUTE_2_SLEWFLAG_VALUE  True


/* Module MUTE_0 Location Start - Non Modulo Location Start*/
#define MUTE_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_0_SWITCH_ADDR  1310720
#define MUTE_0_SWITCH_VALUE  False
#define MUTE_0_SLEWFLAG_ADDR  1310721
#define MUTE_0_SLEWFLAG_VALUE  True


/* Module MULTI_OUTPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_OUTPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/




#endif