#ifndef _PARAM__H__
#define _PARAM__H__


/* Module MULTI_INPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_INPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module SINGLE_VOLUME_0 Location Start - Non Modulo Location Start*/
#define SINGLE_VOLUME_0_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SINGLE_VOLUME_0_VOLUME_ADDR  32768
#define SINGLE_VOLUME_0_VOLUME_VALUE  0


/* Module SPLITTER_SINGLE_0 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_0_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_0_GAIN_ADDR  65536
#define SPLITTER_SINGLE_0_GAIN_VALUE  0.0


/* Module SPLITTER_SINGLE_1 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_1_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_1_GAIN_ADDR  98304
#define SPLITTER_SINGLE_1_GAIN_VALUE  0.0


/* Module MIXER_MULTI_0 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_0_G0_ADDR  131072
#define MIXER_MULTI_0_G0_VALUE  -6.0
#define MIXER_MULTI_0_G1_ADDR  131073
#define MIXER_MULTI_0_G1_VALUE  -6.0


/* Module SPLITTER_SINGLE_2 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_2_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_2_GAIN_ADDR  163840
#define SPLITTER_SINGLE_2_GAIN_VALUE  0.0


/* Module DSP_GAIN_2 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_2_GAIN_ADDR  196608
#define DSP_GAIN_2_GAIN_VALUE  2.0
#define DSP_GAIN_2_TYPE_ADDR  196609
#define DSP_GAIN_2_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_1 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_1_COUNT    45

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_ADDR  229376
#define FILTER_GRAPHICAL_EQ_1_NUMFILTER_VALUE  11
#define FILTER_GRAPHICAL_EQ_1_FC_0_ADDR  229377
#define FILTER_GRAPHICAL_EQ_1_FC_0_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_0_ADDR  229378
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_0_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_0_ADDR  229379
#define FILTER_GRAPHICAL_EQ_1_Q_0_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_0_ADDR  229380
#define FILTER_GRAPHICAL_EQ_1_TYPE_0_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_1_ADDR  229381
#define FILTER_GRAPHICAL_EQ_1_FC_1_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_1_ADDR  229382
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_1_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_1_ADDR  229383
#define FILTER_GRAPHICAL_EQ_1_Q_1_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_1_ADDR  229384
#define FILTER_GRAPHICAL_EQ_1_TYPE_1_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_2_ADDR  229385
#define FILTER_GRAPHICAL_EQ_1_FC_2_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_2_ADDR  229386
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_2_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_2_ADDR  229387
#define FILTER_GRAPHICAL_EQ_1_Q_2_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_2_ADDR  229388
#define FILTER_GRAPHICAL_EQ_1_TYPE_2_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_3_ADDR  229389
#define FILTER_GRAPHICAL_EQ_1_FC_3_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_3_ADDR  229390
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_3_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_3_ADDR  229391
#define FILTER_GRAPHICAL_EQ_1_Q_3_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_3_ADDR  229392
#define FILTER_GRAPHICAL_EQ_1_TYPE_3_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_4_ADDR  229393
#define FILTER_GRAPHICAL_EQ_1_FC_4_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_4_ADDR  229394
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_4_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_4_ADDR  229395
#define FILTER_GRAPHICAL_EQ_1_Q_4_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_4_ADDR  229396
#define FILTER_GRAPHICAL_EQ_1_TYPE_4_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_5_ADDR  229397
#define FILTER_GRAPHICAL_EQ_1_FC_5_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_5_ADDR  229398
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_5_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_5_ADDR  229399
#define FILTER_GRAPHICAL_EQ_1_Q_5_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_5_ADDR  229400
#define FILTER_GRAPHICAL_EQ_1_TYPE_5_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_6_ADDR  229401
#define FILTER_GRAPHICAL_EQ_1_FC_6_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_6_ADDR  229402
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_6_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_6_ADDR  229403
#define FILTER_GRAPHICAL_EQ_1_Q_6_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_6_ADDR  229404
#define FILTER_GRAPHICAL_EQ_1_TYPE_6_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_7_ADDR  229405
#define FILTER_GRAPHICAL_EQ_1_FC_7_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_7_ADDR  229406
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_7_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_1_Q_7_ADDR  229407
#define FILTER_GRAPHICAL_EQ_1_Q_7_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_1_TYPE_7_ADDR  229408
#define FILTER_GRAPHICAL_EQ_1_TYPE_7_VALUE  3
#define FILTER_GRAPHICAL_EQ_1_FC_8_ADDR  229409
#define FILTER_GRAPHICAL_EQ_1_FC_8_VALUE  60.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_8_ADDR  229410
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_8_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_1_Q_8_ADDR  229411
#define FILTER_GRAPHICAL_EQ_1_Q_8_VALUE  1.2
#define FILTER_GRAPHICAL_EQ_1_TYPE_8_ADDR  229412
#define FILTER_GRAPHICAL_EQ_1_TYPE_8_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_FC_9_ADDR  229413
#define FILTER_GRAPHICAL_EQ_1_FC_9_VALUE  85.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_9_ADDR  229414
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_9_VALUE  3.0
#define FILTER_GRAPHICAL_EQ_1_Q_9_ADDR  229415
#define FILTER_GRAPHICAL_EQ_1_Q_9_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_1_TYPE_9_ADDR  229416
#define FILTER_GRAPHICAL_EQ_1_TYPE_9_VALUE  0
#define FILTER_GRAPHICAL_EQ_1_FC_10_ADDR  229417
#define FILTER_GRAPHICAL_EQ_1_FC_10_VALUE  2000.0
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_10_ADDR  229418
#define FILTER_GRAPHICAL_EQ_1_BOOSTDB_10_VALUE  -7.0
#define FILTER_GRAPHICAL_EQ_1_Q_10_ADDR  229419
#define FILTER_GRAPHICAL_EQ_1_Q_10_VALUE  1.7
#define FILTER_GRAPHICAL_EQ_1_TYPE_10_ADDR  229420
#define FILTER_GRAPHICAL_EQ_1_TYPE_10_VALUE  0


/* Module DSP_GAIN_3 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_3_GAIN_ADDR  262144
#define DSP_GAIN_3_GAIN_VALUE  2.0
#define DSP_GAIN_3_TYPE_ADDR  262145
#define DSP_GAIN_3_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_0 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_0_COUNT    53

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_ADDR  294912
#define FILTER_GRAPHICAL_EQ_0_NUMFILTER_VALUE  13
#define FILTER_GRAPHICAL_EQ_0_FC_0_ADDR  294913
#define FILTER_GRAPHICAL_EQ_0_FC_0_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_0_ADDR  294914
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_0_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_0_ADDR  294915
#define FILTER_GRAPHICAL_EQ_0_Q_0_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_0_ADDR  294916
#define FILTER_GRAPHICAL_EQ_0_TYPE_0_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_1_ADDR  294917
#define FILTER_GRAPHICAL_EQ_0_FC_1_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_1_ADDR  294918
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_1_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_1_ADDR  294919
#define FILTER_GRAPHICAL_EQ_0_Q_1_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_1_ADDR  294920
#define FILTER_GRAPHICAL_EQ_0_TYPE_1_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_2_ADDR  294921
#define FILTER_GRAPHICAL_EQ_0_FC_2_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_2_ADDR  294922
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_2_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_2_ADDR  294923
#define FILTER_GRAPHICAL_EQ_0_Q_2_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_2_ADDR  294924
#define FILTER_GRAPHICAL_EQ_0_TYPE_2_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_3_ADDR  294925
#define FILTER_GRAPHICAL_EQ_0_FC_3_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_3_ADDR  294926
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_3_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_3_ADDR  294927
#define FILTER_GRAPHICAL_EQ_0_Q_3_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_3_ADDR  294928
#define FILTER_GRAPHICAL_EQ_0_TYPE_3_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_4_ADDR  294929
#define FILTER_GRAPHICAL_EQ_0_FC_4_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_4_ADDR  294930
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_4_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_4_ADDR  294931
#define FILTER_GRAPHICAL_EQ_0_Q_4_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_4_ADDR  294932
#define FILTER_GRAPHICAL_EQ_0_TYPE_4_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_5_ADDR  294933
#define FILTER_GRAPHICAL_EQ_0_FC_5_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_5_ADDR  294934
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_5_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_5_ADDR  294935
#define FILTER_GRAPHICAL_EQ_0_Q_5_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_5_ADDR  294936
#define FILTER_GRAPHICAL_EQ_0_TYPE_5_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_6_ADDR  294937
#define FILTER_GRAPHICAL_EQ_0_FC_6_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_6_ADDR  294938
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_6_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_6_ADDR  294939
#define FILTER_GRAPHICAL_EQ_0_Q_6_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_6_ADDR  294940
#define FILTER_GRAPHICAL_EQ_0_TYPE_6_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_7_ADDR  294941
#define FILTER_GRAPHICAL_EQ_0_FC_7_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_7_ADDR  294942
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_7_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_7_ADDR  294943
#define FILTER_GRAPHICAL_EQ_0_Q_7_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_0_TYPE_7_ADDR  294944
#define FILTER_GRAPHICAL_EQ_0_TYPE_7_VALUE  4
#define FILTER_GRAPHICAL_EQ_0_FC_8_ADDR  294945
#define FILTER_GRAPHICAL_EQ_0_FC_8_VALUE  2200.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_8_ADDR  294946
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_8_VALUE  -1.5
#define FILTER_GRAPHICAL_EQ_0_Q_8_ADDR  294947
#define FILTER_GRAPHICAL_EQ_0_Q_8_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_0_TYPE_8_ADDR  294948
#define FILTER_GRAPHICAL_EQ_0_TYPE_8_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_FC_9_ADDR  294949
#define FILTER_GRAPHICAL_EQ_0_FC_9_VALUE  7000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_9_ADDR  294950
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_9_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_0_Q_9_ADDR  294951
#define FILTER_GRAPHICAL_EQ_0_Q_9_VALUE  1.5
#define FILTER_GRAPHICAL_EQ_0_TYPE_9_ADDR  294952
#define FILTER_GRAPHICAL_EQ_0_TYPE_9_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_FC_10_ADDR  294953
#define FILTER_GRAPHICAL_EQ_0_FC_10_VALUE  13000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_10_ADDR  294954
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_10_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_0_Q_10_ADDR  294955
#define FILTER_GRAPHICAL_EQ_0_Q_10_VALUE  1.41
#define FILTER_GRAPHICAL_EQ_0_TYPE_10_ADDR  294956
#define FILTER_GRAPHICAL_EQ_0_TYPE_10_VALUE  0
#define FILTER_GRAPHICAL_EQ_0_FC_11_ADDR  294957
#define FILTER_GRAPHICAL_EQ_0_FC_11_VALUE  9000.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_11_ADDR  294958
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_11_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_0_Q_11_ADDR  294959
#define FILTER_GRAPHICAL_EQ_0_Q_11_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_0_TYPE_11_ADDR  294960
#define FILTER_GRAPHICAL_EQ_0_TYPE_11_VALUE  2
#define FILTER_GRAPHICAL_EQ_0_FC_12_ADDR  294961
#define FILTER_GRAPHICAL_EQ_0_FC_12_VALUE  3500.0
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_12_ADDR  294962
#define FILTER_GRAPHICAL_EQ_0_BOOSTDB_12_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_0_Q_12_ADDR  294963
#define FILTER_GRAPHICAL_EQ_0_Q_12_VALUE  1.5
#define FILTER_GRAPHICAL_EQ_0_TYPE_12_ADDR  294964
#define FILTER_GRAPHICAL_EQ_0_TYPE_12_VALUE  1


/* Module LIMITER_0 Location Start - Non Modulo Location Start*/
#define LIMITER_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_0_RMSTC_ADDR  327680
#define LIMITER_0_RMSTC_VALUE  20.0
#define LIMITER_0_DECAYTIME_ADDR  327681
#define LIMITER_0_DECAYTIME_VALUE  200.0
#define LIMITER_0_THRESHOLD_ADDR  327682
#define LIMITER_0_THRESHOLD_VALUE  -12.5


/* Module DSP_GAIN_1 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_1_GAIN_ADDR  360448
#define DSP_GAIN_1_GAIN_VALUE  0.0
#define DSP_GAIN_1_TYPE_ADDR  360449
#define DSP_GAIN_1_TYPE_VALUE  0


/* Module MUTE_3 Location Start - Non Modulo Location Start*/
#define MUTE_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_3_SWITCH_ADDR  393216
#define MUTE_3_SWITCH_VALUE  False
#define MUTE_3_SLEWFLAG_ADDR  393217
#define MUTE_3_SLEWFLAG_VALUE  True


/* Module LIMITER_1 Location Start - Non Modulo Location Start*/
#define LIMITER_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_1_RMSTC_ADDR  425984
#define LIMITER_1_RMSTC_VALUE  20.0
#define LIMITER_1_DECAYTIME_ADDR  425985
#define LIMITER_1_DECAYTIME_VALUE  1500.0
#define LIMITER_1_THRESHOLD_ADDR  425986
#define LIMITER_1_THRESHOLD_VALUE  -12.5


/* Module DSP_GAIN_4 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_4_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_4_GAIN_ADDR  458752
#define DSP_GAIN_4_GAIN_VALUE  0.0
#define DSP_GAIN_4_TYPE_ADDR  458753
#define DSP_GAIN_4_TYPE_VALUE  0


/* Module FILTER_GRAPHICAL_EQ_2 Location Start - Non Modulo Location Start*/
#define FILTER_GRAPHICAL_EQ_2_COUNT    53

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_GRAPHICAL_EQ_2_NUMFILTER_ADDR  491520
#define FILTER_GRAPHICAL_EQ_2_NUMFILTER_VALUE  13
#define FILTER_GRAPHICAL_EQ_2_FC_0_ADDR  491521
#define FILTER_GRAPHICAL_EQ_2_FC_0_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_0_ADDR  491522
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_0_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_0_ADDR  491523
#define FILTER_GRAPHICAL_EQ_2_Q_0_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_0_ADDR  491524
#define FILTER_GRAPHICAL_EQ_2_TYPE_0_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_1_ADDR  491525
#define FILTER_GRAPHICAL_EQ_2_FC_1_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_1_ADDR  491526
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_1_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_1_ADDR  491527
#define FILTER_GRAPHICAL_EQ_2_Q_1_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_1_ADDR  491528
#define FILTER_GRAPHICAL_EQ_2_TYPE_1_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_2_ADDR  491529
#define FILTER_GRAPHICAL_EQ_2_FC_2_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_2_ADDR  491530
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_2_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_2_ADDR  491531
#define FILTER_GRAPHICAL_EQ_2_Q_2_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_2_ADDR  491532
#define FILTER_GRAPHICAL_EQ_2_TYPE_2_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_3_ADDR  491533
#define FILTER_GRAPHICAL_EQ_2_FC_3_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_3_ADDR  491534
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_3_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_3_ADDR  491535
#define FILTER_GRAPHICAL_EQ_2_Q_3_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_3_ADDR  491536
#define FILTER_GRAPHICAL_EQ_2_TYPE_3_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_4_ADDR  491537
#define FILTER_GRAPHICAL_EQ_2_FC_4_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_4_ADDR  491538
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_4_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_4_ADDR  491539
#define FILTER_GRAPHICAL_EQ_2_Q_4_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_4_ADDR  491540
#define FILTER_GRAPHICAL_EQ_2_TYPE_4_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_5_ADDR  491541
#define FILTER_GRAPHICAL_EQ_2_FC_5_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_5_ADDR  491542
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_5_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_5_ADDR  491543
#define FILTER_GRAPHICAL_EQ_2_Q_5_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_5_ADDR  491544
#define FILTER_GRAPHICAL_EQ_2_TYPE_5_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_6_ADDR  491545
#define FILTER_GRAPHICAL_EQ_2_FC_6_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_6_ADDR  491546
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_6_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_6_ADDR  491547
#define FILTER_GRAPHICAL_EQ_2_Q_6_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_6_ADDR  491548
#define FILTER_GRAPHICAL_EQ_2_TYPE_6_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_7_ADDR  491549
#define FILTER_GRAPHICAL_EQ_2_FC_7_VALUE  600.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_7_ADDR  491550
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_7_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_7_ADDR  491551
#define FILTER_GRAPHICAL_EQ_2_Q_7_VALUE  0.71
#define FILTER_GRAPHICAL_EQ_2_TYPE_7_ADDR  491552
#define FILTER_GRAPHICAL_EQ_2_TYPE_7_VALUE  4
#define FILTER_GRAPHICAL_EQ_2_FC_8_ADDR  491553
#define FILTER_GRAPHICAL_EQ_2_FC_8_VALUE  2200.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_8_ADDR  491554
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_8_VALUE  -1.5
#define FILTER_GRAPHICAL_EQ_2_Q_8_ADDR  491555
#define FILTER_GRAPHICAL_EQ_2_Q_8_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_2_TYPE_8_ADDR  491556
#define FILTER_GRAPHICAL_EQ_2_TYPE_8_VALUE  0
#define FILTER_GRAPHICAL_EQ_2_FC_9_ADDR  491557
#define FILTER_GRAPHICAL_EQ_2_FC_9_VALUE  7000.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_9_ADDR  491558
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_9_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_2_Q_9_ADDR  491559
#define FILTER_GRAPHICAL_EQ_2_Q_9_VALUE  1.5
#define FILTER_GRAPHICAL_EQ_2_TYPE_9_ADDR  491560
#define FILTER_GRAPHICAL_EQ_2_TYPE_9_VALUE  0
#define FILTER_GRAPHICAL_EQ_2_FC_10_ADDR  491561
#define FILTER_GRAPHICAL_EQ_2_FC_10_VALUE  13000.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_10_ADDR  491562
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_10_VALUE  0.0
#define FILTER_GRAPHICAL_EQ_2_Q_10_ADDR  491563
#define FILTER_GRAPHICAL_EQ_2_Q_10_VALUE  1.41
#define FILTER_GRAPHICAL_EQ_2_TYPE_10_ADDR  491564
#define FILTER_GRAPHICAL_EQ_2_TYPE_10_VALUE  0
#define FILTER_GRAPHICAL_EQ_2_FC_11_ADDR  491565
#define FILTER_GRAPHICAL_EQ_2_FC_11_VALUE  9000.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_11_ADDR  491566
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_11_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_2_Q_11_ADDR  491567
#define FILTER_GRAPHICAL_EQ_2_Q_11_VALUE  1.0
#define FILTER_GRAPHICAL_EQ_2_TYPE_11_ADDR  491568
#define FILTER_GRAPHICAL_EQ_2_TYPE_11_VALUE  2
#define FILTER_GRAPHICAL_EQ_2_FC_12_ADDR  491569
#define FILTER_GRAPHICAL_EQ_2_FC_12_VALUE  3500.0
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_12_ADDR  491570
#define FILTER_GRAPHICAL_EQ_2_BOOSTDB_12_VALUE  -3.0
#define FILTER_GRAPHICAL_EQ_2_Q_12_ADDR  491571
#define FILTER_GRAPHICAL_EQ_2_Q_12_VALUE  1.5
#define FILTER_GRAPHICAL_EQ_2_TYPE_12_ADDR  491572
#define FILTER_GRAPHICAL_EQ_2_TYPE_12_VALUE  1


/* Module SPLITTER_SINGLE_4 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_4_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_4_GAIN_ADDR  524288
#define SPLITTER_SINGLE_4_GAIN_VALUE  0.0


/* Module ARITH_INVERT_1 Location Start - Non Modulo Location Start*/
#define ARITH_INVERT_1_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module SPLITTER_SINGLE_3 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_3_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_3_GAIN_ADDR  589824
#define SPLITTER_SINGLE_3_GAIN_VALUE  0.0


/* Module MIXER_MULTI_3 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_3_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_3_G0_ADDR  622592
#define MIXER_MULTI_3_G0_VALUE  1.0
#define MIXER_MULTI_3_G1_ADDR  622593
#define MIXER_MULTI_3_G1_VALUE  1.0


/* Module SPLITTER_SINGLE_5 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_5_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_5_GAIN_ADDR  655360
#define SPLITTER_SINGLE_5_GAIN_VALUE  0.0


/* Module MIXER_MULTI_1 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_1_G0_ADDR  688128
#define MIXER_MULTI_1_G0_VALUE  -3.7
#define MIXER_MULTI_1_G1_ADDR  688129
#define MIXER_MULTI_1_G1_VALUE  0.0


/* Module ARITH_INVERT_0 Location Start - Non Modulo Location Start*/
#define ARITH_INVERT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/


/* Module MIXER_MULTI_2 Location Start - Non Modulo Location Start*/
#define MIXER_MULTI_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MIXER_MULTI_2_G0_ADDR  753664
#define MIXER_MULTI_2_G0_VALUE  -3.7
#define MIXER_MULTI_2_G1_ADDR  753665
#define MIXER_MULTI_2_G1_VALUE  0.0


/* Module MUXES_SWITCH_STEREO_0 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_STEREO_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_STEREO_0_IDX_ADDR  786432
#define MUXES_SWITCH_STEREO_0_IDX_VALUE  0
#define MUXES_SWITCH_STEREO_0_SLEWFLAG_ADDR  786433
#define MUXES_SWITCH_STEREO_0_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_STEREO_0_SLEWRATE_ADDR  786434
#define MUXES_SWITCH_STEREO_0_SLEWRATE_VALUE  12


/* Module REVERB_0 Location Start - Non Modulo Location Start*/
#define REVERB_0_COUNT    6

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define REVERB_0_ENABLE_ADDR  819200
#define REVERB_0_ENABLE_VALUE  1
#define REVERB_0_DRYLEVEL_ADDR  819201
#define REVERB_0_DRYLEVEL_VALUE  80.0
#define REVERB_0_WETLEVEL_ADDR  819202
#define REVERB_0_WETLEVEL_VALUE  20.0
#define REVERB_0_ROOMSIZE_ADDR  819203
#define REVERB_0_ROOMSIZE_VALUE  0.65
#define REVERB_0_DAMP_ADDR  819204
#define REVERB_0_DAMP_VALUE  0.2
#define REVERB_0_WIDTH_ADDR  819205
#define REVERB_0_WIDTH_VALUE  60.0


/* Module MUXES_SWITCH_STEREO_1 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_STEREO_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_STEREO_1_IDX_ADDR  851968
#define MUXES_SWITCH_STEREO_1_IDX_VALUE  1
#define MUXES_SWITCH_STEREO_1_SLEWFLAG_ADDR  851969
#define MUXES_SWITCH_STEREO_1_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_STEREO_1_SLEWRATE_ADDR  851970
#define MUXES_SWITCH_STEREO_1_SLEWRATE_VALUE  12


/* Module DSP_GAIN_6 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_6_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_6_GAIN_ADDR  884736
#define DSP_GAIN_6_GAIN_VALUE  2.0
#define DSP_GAIN_6_TYPE_ADDR  884737
#define DSP_GAIN_6_TYPE_VALUE  0


/* Module LIMITER_3 Location Start - Non Modulo Location Start*/
#define LIMITER_3_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_3_RMSTC_ADDR  917504
#define LIMITER_3_RMSTC_VALUE  20.0
#define LIMITER_3_DECAYTIME_ADDR  917505
#define LIMITER_3_DECAYTIME_VALUE  200.0
#define LIMITER_3_THRESHOLD_ADDR  917506
#define LIMITER_3_THRESHOLD_VALUE  -12.5


/* Module SPLITTER_SINGLE_7 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_7_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_7_GAIN_ADDR  950272
#define SPLITTER_SINGLE_7_GAIN_VALUE  0.0


/* Module MUTE_1 Location Start - Non Modulo Location Start*/
#define MUTE_1_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_1_SWITCH_ADDR  983040
#define MUTE_1_SWITCH_VALUE  False
#define MUTE_1_SLEWFLAG_ADDR  983041
#define MUTE_1_SLEWFLAG_VALUE  True


/* Module DSP_GAIN_5 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_5_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_5_GAIN_ADDR  1015808
#define DSP_GAIN_5_GAIN_VALUE  2.0
#define DSP_GAIN_5_TYPE_ADDR  1015809
#define DSP_GAIN_5_TYPE_VALUE  0


/* Module LIMITER_2 Location Start - Non Modulo Location Start*/
#define LIMITER_2_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define LIMITER_2_RMSTC_ADDR  1048576
#define LIMITER_2_RMSTC_VALUE  20.0
#define LIMITER_2_DECAYTIME_ADDR  1048577
#define LIMITER_2_DECAYTIME_VALUE  200.0
#define LIMITER_2_THRESHOLD_ADDR  1048578
#define LIMITER_2_THRESHOLD_VALUE  -12.5


/* Module SPLITTER_SINGLE_6 Location Start - Non Modulo Location Start*/
#define SPLITTER_SINGLE_6_COUNT    1

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define SPLITTER_SINGLE_6_GAIN_ADDR  1081344
#define SPLITTER_SINGLE_6_GAIN_VALUE  0.0


/* Module MUXES_SWITCH_MONO_0 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_MONO_0_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_MONO_0_IDX_ADDR  1114112
#define MUXES_SWITCH_MONO_0_IDX_VALUE  0
#define MUXES_SWITCH_MONO_0_SLEWFLAG_ADDR  1114113
#define MUXES_SWITCH_MONO_0_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_MONO_0_SLEWRATE_ADDR  1114114
#define MUXES_SWITCH_MONO_0_SLEWRATE_VALUE  12


/* Module MUTE_4 Location Start - Non Modulo Location Start*/
#define MUTE_4_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_4_SWITCH_ADDR  1146880
#define MUTE_4_SWITCH_VALUE  False
#define MUTE_4_SLEWFLAG_ADDR  1146881
#define MUTE_4_SLEWFLAG_VALUE  True


/* Module MUXES_SWITCH_MONO_1 Location Start - Non Modulo Location Start*/
#define MUXES_SWITCH_MONO_1_COUNT    3

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUXES_SWITCH_MONO_1_IDX_ADDR  1179648
#define MUXES_SWITCH_MONO_1_IDX_VALUE  0
#define MUXES_SWITCH_MONO_1_SLEWFLAG_ADDR  1179649
#define MUXES_SWITCH_MONO_1_SLEWFLAG_VALUE  1
#define MUXES_SWITCH_MONO_1_SLEWRATE_ADDR  1179650
#define MUXES_SWITCH_MONO_1_SLEWRATE_VALUE  12


/* Module MUTE_2 Location Start - Non Modulo Location Start*/
#define MUTE_2_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_2_SWITCH_ADDR  1212416
#define MUTE_2_SWITCH_VALUE  False
#define MUTE_2_SLEWFLAG_ADDR  1212417
#define MUTE_2_SLEWFLAG_VALUE  True


/* Module MUTE_0 Location Start - Non Modulo Location Start*/
#define MUTE_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_0_SWITCH_ADDR  1245184
#define MUTE_0_SWITCH_VALUE  False
#define MUTE_0_SLEWFLAG_ADDR  1245185
#define MUTE_0_SLEWFLAG_VALUE  True


/* Module FILTER_2ND_GENERAL_0 Location Start - Non Modulo Location Start*/
#define FILTER_2ND_GENERAL_0_COUNT    7

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define FILTER_2ND_GENERAL_0_ENABLE_ADDR  1277952
#define FILTER_2ND_GENERAL_0_ENABLE_VALUE  1
#define FILTER_2ND_GENERAL_0_POLARITY_ADDR  1277953
#define FILTER_2ND_GENERAL_0_POLARITY_VALUE  0
#define FILTER_2ND_GENERAL_0_TYPE_ADDR  1277954
#define FILTER_2ND_GENERAL_0_TYPE_VALUE  1
#define FILTER_2ND_GENERAL_0_GAINDB_ADDR  1277955
#define FILTER_2ND_GENERAL_0_GAINDB_VALUE  0.0
#define FILTER_2ND_GENERAL_0_FC_ADDR  1277956
#define FILTER_2ND_GENERAL_0_FC_VALUE  75.0
#define FILTER_2ND_GENERAL_0_Q_ADDR  1277957
#define FILTER_2ND_GENERAL_0_Q_VALUE  0.6
#define FILTER_2ND_GENERAL_0_BOOSTDB_ADDR  1277958
#define FILTER_2ND_GENERAL_0_BOOSTDB_VALUE  -2.5


/* Module DSP_GAIN_0 Location Start - Non Modulo Location Start*/
#define DSP_GAIN_0_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define DSP_GAIN_0_GAIN_ADDR  1310720
#define DSP_GAIN_0_GAIN_VALUE  0.0
#define DSP_GAIN_0_TYPE_ADDR  1310721
#define DSP_GAIN_0_TYPE_VALUE  0


/* Module MUTE_5 Location Start - Non Modulo Location Start*/
#define MUTE_5_COUNT    2

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/
#define MUTE_5_SWITCH_ADDR  1343488
#define MUTE_5_SWITCH_VALUE  False
#define MUTE_5_SLEWFLAG_ADDR  1343489
#define MUTE_5_SLEWFLAG_VALUE  True


/* Module MULTI_OUTPUT_0 Location Start - Non Modulo Location Start*/
#define MULTI_OUTPUT_0_COUNT    0

/* Module Coefficient Offset Location Start - Coefficient Offset Location Start*/




#endif